Fix #17, update code coverage for fm_cmd_utils.c
nasa/FM pull request #33
Opened 2022-06-08 20:31 UTC by havencarlson

**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/FM/blob/main/CONTRIBUTING.md).
* [X] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- part #17 
Updated unit tests for fm_cmd_utils.c to cover LoadOpenFileData, SearchOpenFileData, and branches.

**Testing performed**
Steps taken to test the contribution:
1. lcov --capture --rc lcov_branch_coverage=1 --directory build --output-file coverage_test.info
2. lcov --rc lcov_branch_coverage=1 --add-tracefile coverage_base.info --add-tracefile coverage_test.info --output-file coverage_total.info
3. genhtml coverage_total.info --branch-coverage --output-directory lcov

**Expected behavior changes**
no impact to behavior

**System(s) tested on**
 - OS: Ubuntu 18.04

**Additional context**
Add any other context about the contribution here.

**Third party code**
If included, identify any third party code and provide text file of license

**Contributor Info - All information REQUIRED for consideration of pull request**
Full name and company/organization/center of all contributors ("Personal" if individual work)
 - Note CLA's apply to software contributions.

2022-06-10 05:34 UTC, astrogeco commented
@havencarlson this needs a run through clang format to fix white space. You can also fix it manually by looking at the output of the format check workflow

2022-06-10 12:51 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    strncpy(dummy_files_data[0].LogicalName, InitialName, OS_MAX_API_NAME);
Add memset(dummy_files_data, 0, sizeof(dummy_files_data) to ensure the structure is fully initialized before use

2022-06-10 12:51 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    uint32 open_file_count = FM_GetOpenFilesData(dummy_files_data);
Combine this with line 198... just assert the return

2022-06-10 12:58 UTC, skliper reviewed
Comments apply to patterns throughout the change.  Avoid UtAssert_True, UT_GetStubCount, etc in favor of the macros that standardize the report information.  Ensure variables are initialized before use, etc.

2022-06-10 12:58 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    uint8 call_count_GetTaskInfo = UT_GetStubCount(UT_KEY(OS_TaskGetInfo));
Use UtAssert_STUB_COUNT

2022-06-10 12:58 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    uint32 strCmpAppNameResult = strncmp(dummy_files_data[0].AppName, InitialName, OS_MAX_API_NAME);
Use UtAssert_STRINGBUF_EQ

2022-06-10 12:58 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +void Test_FM_GetOpenFilesData_ObjIdIsNull(void)
This name doesn't seem to match?  Object ID is undefined

2022-06-10 12:58 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    FM_OpenFilesEntry_t dummy_files_data[1];
memset to zero before use

2022-06-15 22:53 UTC, skliper reviewed
Great work!  Just a few minor updates recommended.  Happy to chat if it helps.

2022-06-15 22:53 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    uint32 open_file_count = FM_GetOpenFilesData(dummy_files_data);
`UtAssert_UINT32_EQ(FM_GetOpenFilesData(dummy_files_data), 1);`

Remove open_file_count declaration and the test below.  Same pattern for the rest of the tests.

2022-06-15 22:53 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    uint8 count_osstat      = UT_GetStubCount(UT_KEY(OS_stat));
Updated code should use UtAssert_STUB_COUNT (applies below).

2022-06-15 22:53 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    UtAssert_True(open_file_count == 0, "OpenFileCount is %u and should be 0", open_file_count);
Just UtAssert_UINT32_EQ(FM_GetOpenFilesData(dummy_files_data), 0); and remove the unnecessary local open_file_count.

2022-06-16 17:41 UTC, skliper requested changes

2022-06-16 17:41 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
> +    uint32 filename_state = FM_GetFilenameState(dummy_filename, dummy_bufsize, dummy_fileinfo);
UtAssert_UINT32_EQ(FM_GetFilenameState(dummy_filename, dummy_bufsize, dummy_fileinfo), FM_NAME_IS_INVALID); and remove assert below... and for the rest of the occurrences of this pattern

2022-06-16 17:41 UTC, skliper commented on unit-test/fm_cmd_utils_tests.c
>      uint8 count_osforeachobject = UT_GetStubCount(UT_KEY(OS_ForEachObject));
Worth the quick cleanup of these (and in the other functions touched below).  Declaration mid-function is a coding standards violation.  No need to fix in functions you don't touch, but good to fix the ones you do modify.

2022-06-17 13:56 UTC, skliper approved these changes
Perfect, great work!

2022-06-17 13:57 UTC, skliper commented
@astrogeco - should be ready to merge... we'll need to update the workflow allowed missed branches/lines once these are all in.

2022-06-17 15:29 UTC, astrogeco commented
@chillfig Still need some format fixes

2022-06-17 23:19 UTC, astrogeco commented
[CCB:2022-06-08](https://github.com/nasa/cFS/wiki/CCB:-2022.06.15) APPROVED

2022-06-17 23:40 UTC, merged