Fix #92, Use size_t for 'size' variables
nasa/FM pull request #93
Opened 2023-03-10 10:10 UTC by thnkslprpt

**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #92 
Easy-to-find size variables converted to `size_t` type.

All except the local variables in `FM_ChildDirListPktCmd()` and `FM_ChildDirListFileLoop()` were already of type `uint32`, so no real risk of signedness issues popping up.

Note: I did not scrub the entire app - if someone can suggest some additional variables to convert over to `size_t` I can add them to this PR.

A few typos and spacing issues cleared up in the same files.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.

**Expected behavior changes**
Variables representing size should use `size_t` where possible - more expressive and more compliant with the various (relevant) coding guidelines.

**Contributor Info**
Avi Weiss @thnkslprpt

2023-03-16 18:51 UTC, dzbaker requested changes

2023-03-16 18:51 UTC, dzbaker commented on fsw/src/fm_cmd_utils.h
> + *       If the Child Task is operational then it is signalled via
Signaled is actually the correct spelling (in American English; British English uses 2 'l's)

2023-03-16 22:18 UTC, thnkslprpt commented on fsw/src/fm_cmd_utils.h
> + *       If the Child Task is operational then it is signalled via
Woops - don't know how that snuck in there.
My family is a hybrid of both sides of the Atlantic...
Changed back now :-)

2023-03-17 10:40 UTC, dzbaker approved these changes

2023-03-30 18:36 UTC, dzbaker commented
@thnkslprpt CCB 30 March 2023: Approved pending conflict resolution.

2023-03-30 20:42 UTC, thnkslprpt commented
> @thnkslprpt CCB 30 March 2023: Approved pending conflict resolution.

All done @dzbaker.
Cheers

2023-03-30 20:49 UTC, merged